
stages:
  - test

unit-test-job:
  stage: test
  before_script:
    - cd final-deliverable
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  script:
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
