
stages:
  - test

test:
  stage: test
  before_script:
    - cd final-deliverable
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  script:
    - pnpm test
  cache:
    key:
      files:
        - final-deliverable/pnpm-lock.yaml
    paths:
      - final-deliverable/.pnpm-store
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

